receivers:
  dockerstats:
    endpoint: unix:///var/run/docker.sock
    collection_interval: 10s
    excluded_images:
      - "otel/opentelemetry-collector"

processors:
  batch:

exporters:
  otlp:
    endpoint: "signoz-otel-collector:4317"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [dockerstats]
      processors: [batch]
      exporters: [otlp]
